<a href="https://colab.research.google.com/github/Fatmaerdogan/AA-Clone/blob/main/10_05_2025_Python_dersi_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY



In [ ]:
import numpy as np

In [ ]:
dsd

## Array yaratmak


Python listlerine benzeyen, aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

In [ ]:
x= np.array([1,2,3,4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
m= np.array(["a","b","c"])

In [ ]:
m

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
n= np.array([1,2,3,"a"])

In [ ]:
# eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n

array(['1', '2', '3', 'a'], dtype='<U11')

In [ ]:
# 1 tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [ ]:
z

array([1. , 2. , 3. , 3.5])

## Array data tipini belirleme

In [ ]:
x=np.array([1,2,3.4])

In [ ]:
x

array([1. , 2. , 3.4])

In [ ]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [ ]:
x

array([1, 2, 3])

In [ ]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [ ]:
y

array(['1', '2', '3.4'], dtype='<U3')

In [ ]:
y=np.array([1,2,"a"], dtype="int32")  #str olduğu için integer hale getiremeyiz.

ValueError: invalid literal for int() with base 10: 'a'

## Elemanları 0 olan array

In [ ]:
?np #içeriğe erişme

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#3 satır(row) ve 5 sütun(kolon)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 2 boyutlu 3x5 lik array
x= np.zeros([3,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 3 boyutlu
# 4 tane 5x7 lik array kur
y= np.zeros([4,5,7])
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

## array bilgilerine erişme

In [ ]:
x.shape

(3, 5)

In [ ]:
y.shape

(4, 5, 7)

In [ ]:
#boyut
x.ndim

2

In [ ]:
#boyut
y.ndim

3

In [ ]:
#array içindeki eleman (3*5)
x.size

15

In [ ]:
y.size (# 4*5*7)

140

### np.full

In [ ]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

### ardışık sayılardan array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

## aralığı eşit uzaklıkta bölerek array oluşturma

verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil, aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur. (linspace)

In [ ]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
np.linspace(1,2).ndim

1

In [ ]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [ ]:
np.linspace(1.5,3, num=3)

## Normal Dağılıma Uygun değerler ile array oluşturma

In [ ]:
np.random.normal(mean, std, array shape)

In [ ]:
np.random.normal(0,1, (3,5)) #0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[ 0.30879339,  0.69591678,  1.02929836, -0.03632739,  1.59626977],
       [-0.64155555, -0.89470999, -1.73926101,  0.18426095,  0.15600657],
       [-1.20096586,  1.22813036, -0.76774534, -0.42549459, -0.55022683]])

In [ ]:
np.random.normal(0,100, (3,5))

array([[  -6.32956824,  -44.53167852, -106.88567395,   74.68394458,
          13.44692082],
       [  19.47336638,  110.04916234,   56.90886311, -155.98457725,
          46.28351186],
       [  21.96581271,    1.546816  ,   84.83154696,   16.79794777,
          -1.00911108]])

## Random olarak

In [ ]:
# np.random.randint(low,high)
# 15 dahil değil

np.random.randint(1,15,(3,5))

array([[14,  2,  5,  2,  6],
       [ 1,  9,  6,  4,  6],
       [10,  5,  5,  5, 11]])

In [ ]:

np.random.randint(5,15,(3,5))

array([[10,  7, 10, 11,  5],
       [13, 10, 14,  9, 12],
       [ 6, 10,  6,  8, 12]])

In [ ]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Matematiksel İşlemler

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
x*y

array([ 4, 10, 18])

In [ ]:
x+y

array([5, 7, 9])

In [ ]:
print(x+y)

[5 7 9]


In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
#matris gibi çarpım yapar. (dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))


[[ 6  7]
 [ 8  6]
 [13 11]]


## Reshape

In [ ]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
m.reshape(3,5) #3*5= 15 olduğundan 15!= m olduğundan hata aldık.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [ ]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#otomatik olarak 4 kolonlu bir array yarattı
n.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# concatenate

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
l=[9,0]

In [ ]:
np.concatenate([y,x,l])

array([4, 5, 6, 1, 2, 3, 9, 0])

In [ ]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#asis = 0 satır boyunca
m= np.concatenate([a,a],axis=0)
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#axis= 1 sutun boyunca işlem
m= np.concatenate([a,a],axis=1)
m

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting

In [ ]:
l=[10,20,30,40,50,60,70,80] #list

In [ ]:
l[0:5]

[10, 20, 30, 40, 50]

In [ ]:
l[:5]

[10, 20, 30, 40, 50]

In [ ]:
final=np.split(l,[2,5])
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [ ]:
a,b,c=final

In [ ]:
a,b,c=np.split(l,[2,5])

In [ ]:
a

array([10, 20])

In [ ]:
b

array([30, 40, 50])

In [ ]:
c

array([60, 70, 80])

# Array elemanlarına erişmek

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [ ]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [ ]:
#0.satır 0.kolon
a[0,0]

1

In [ ]:
#0.satır 0.kolon
a[0][0]

1

In [ ]:
#0.satır 1.kolon
a[0,1]

2

In [ ]:
a[1,1]

6

In [ ]:
#2.satır 2.kolon
a[2,2]

11

In [ ]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

### Slice indeksing

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#bütün satırları al ama 2.indexteki kolonu al
a[:,2]

array([ 3,  7, 11])

In [ ]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0:2,2]

array([3, 7])

# filter

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a<7

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [ ]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
filt= a<5

In [ ]:
a[filt]

array([1, 2, 3, 4])

In [ ]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [ ]:
a[filt]

array([6, 7, 8])

In [ ]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [ ]:
a[filt]

array([1, 2, 3, 4, 9])

In [ ]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [ ]:
a[filt]

array([5, 6, 7, 8, 9])

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 7 den küçük elanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

# SUM

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#bütün elemanları topluyor.
np.sum(b)

45

In [ ]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

21

In [ ]:
# sütunların toplamı
np.sum(b,axis=0)

array([12, 15, 18])

In [ ]:
# satırların toplamı
np.sum(b,axis=1)

array([ 6, 15, 24])